-- Existing links from the previous public download page. Safe to re-run.
begin;
insert into public.dropdown_free_downloads(title,description,file_type,thumbnail_url,file_url) select 'Dubstep Drum Kit','Dubstep Drum Kit per qualsiasi DAW. Campioni di batteria ed effetti di alta qualità pronti all''uso.','sample-pack','/images/downloads/dubstep_drum_kit.jpg','https://dropdownacademy.gumroad.com/l/dubstepdrumkit' where not exists (select 1 from public.dropdown_free_downloads where file_url='https://dropdownacademy.gumroad.com/l/dubstepdrumkit');
insert into public.dropdown_free_downloads(title,description,file_type,thumbnail_url,file_url) select 'House Drum Kit','House Drum Kit per qualsiasi DAW. Cassa, rullanti, hi-hat e loop ideali per produzioni house.','sample-pack','/images/downloads/house_drum_kit.jpg','https://dropdownacademy.gumroad.com/l/HouseDrumKit' where not exists (select 1 from public.dropdown_free_downloads where file_url='https://dropdownacademy.gumroad.com/l/HouseDrumKit');
insert into public.dropdown_free_downloads(title,description,file_type,thumbnail_url,file_url) select 'Serum Preset Pack - Synthwave','Preset Pack di Synthwave e retrowave avanzati per il sintetizzatore Serum.','preset','/images/downloads/synthwave_presets.jpg','https://drive.google.com/file/d/1m4JzUWSt9v0MpLNRktsQKv8EDu-2tsrC/view?usp=sharing' where not exists (select 1 from public.dropdown_free_downloads where file_url='https://drive.google.com/file/d/1m4JzUWSt9v0MpLNRktsQKv8EDu-2tsrC/view?usp=sharing');
insert into public.dropdown_free_downloads(title,description,file_type,thumbnail_url,file_url) select 'Vital Preset Pack','Pack di preset professionali e sonorità moderne per il sintetizzatore gratuito Vital.','preset','/images/downloads/vital_presets.jpg','https://drive.google.com/file/d/1NQAQfFC0sAmmWMfHwn83aaaOJ5ZiaKiM/view?usp=sharing' where not exists (select 1 from public.dropdown_free_downloads where file_url='https://drive.google.com/file/d/1NQAQfFC0sAmmWMfHwn83aaaOJ5ZiaKiM/view?usp=sharing');
insert into public.dropdown_free_downloads(title,description,file_type,thumbnail_url,file_url) select 'Moog Model D Plugin per Reaktor','Emulazione software del leggendario sintetizzatore Moog Model D costruita interamente in Reaktor.','template','/images/downloads/moog_model_d.jpg','https://drive.google.com/file/d/171E20oK3-eHw2OONLk479LlXU-5bsf19/view?usp=sharing' where not exists (select 1 from public.dropdown_free_downloads where file_url='https://drive.google.com/file/d/171E20oK3-eHw2OONLk479LlXU-5bsf19/view?usp=sharing');
insert into public.dropdown_free_downloads(title,description,file_type,thumbnail_url,file_url) select 'Korg MS-20 Plugin per Reaktor','Emulazione software del classico sintetizzatore semi-modulare Korg MS-20 in Reaktor.','template','/images/downloads/korg_ms20.jpg','https://drive.google.com/file/d/1tghrXU5uCfAro2TTXSF4mMjxt2fOygGM/view?usp=sharing' where not exists (select 1 from public.dropdown_free_downloads where file_url='https://drive.google.com/file/d/1tghrXU5uCfAro2TTXSF4mMjxt2fOygGM/view?usp=sharing');
insert into public.dropdown_free_downloads(title,description,file_type,thumbnail_url,file_url) select 'Guida Pratica Costruzione 808 Bass','Guida pdf completa + sample pack per imparare a sintetizzare e processare bassi 808 professionali.','template','/images/downloads/guida_808.jpg','https://drive.google.com/file/d/1BhPgNm4PBAoQ1bR289nWPv7lteJbLA6E/view?usp=sharing' where not exists (select 1 from public.dropdown_free_downloads where file_url='https://drive.google.com/file/d/1BhPgNm4PBAoQ1bR289nWPv7lteJbLA6E/view?usp=sharing');
commit;
